import { ConfigProp } from "../BaseRepository";
import { PaymentResponseData } from "./data";

export const paymentConfig: ConfigProp<PaymentResponseData> = {
  fillables: [
    "user_id",
    "department_id",
    "workflow_id",
    "document_category_id",
    "document_type_id",
    "payment_batch_id",
    "expenditure_id",
    "narration",
    "total_amount_payable",
    "payable_id",
    "payable_type",
    "payment_method",
    "type",
    "currency",
    "period",
    "budget_year",
    "beneficiary",
    "transaction_type",
    "transaction_date",
    "total_amount_paid",
    "total_approved_amount",
    "total_taxable_amount",
    "chart_of_account_id",
  ],
  associatedResources: [{ name: "chartOfAccounts", url: "chartOfAccounts" }],
  state: {
    id: 0,
    user_id: 0,
    department_id: 0,
    ledger_id: 0,
    workflow_id: 0,
    chart_of_account_id: 0,
    beneficiary: "",
    document_category_id: 0,
    document_type_id: 0,
    document_draft_id: 0,
    process_card_id: 0,
    payment_batch_id: 0,
    expenditure_id: 0,
    narration: "",
    total_amount_payable: "",
    total_amount_paid: 0,
    total_approved_amount: 0,
    total_taxable_amount: 0,
    payable_id: 0,
    payable_type: "",
    payment_method: "bank-transfer",
    transaction_date: "",
    type: "staff",
    currency: "NGN",
    period: "",
    budget_year: 0,
    transaction_type: "debit",
    resource_id: 0,
    resource_type: "",
    process_metadata: null,
    auto_generated: false,
    requires_settlement: false,
    is_settled: false,
  },
  actions: [
    {
      label: "manage",
      icon: "ri-settings-3-line",
      variant: "success",
      conditions: [],
      operator: "and",
      display: "Manage",
    },
  ],
};
