import { ConfigProp } from "../BaseRepository";
import { DocumentCategoryResponseData } from "./data";

export const documentCategoryConfig: ConfigProp<DocumentCategoryResponseData> =
  {
    fillables: [
      "name",
      "description",
      "document_type_id",
      "icon",
      "workflow_id",
      "selectedRequirements",
      "type",
      "selectedBlocks",
      "service",
      "workflow",
      "config",
      "content",
      "meta_data",
      "signature_type",
      "with_date",
    ],
    associatedResources: [
      { url: "apiServices", name: "services" },
      { name: "documentTypes", url: "documentTypes" },
      { name: "workflows", url: "workflows" },
      { name: "documentRequirements", url: "documentRequirements" },
      { name: "blocks", url: "blocks" },
      { name: "groups", url: "groups" },
      { name: "departments", url: "departments" },
      { name: "users", url: "users" },
      { name: "workflowStages", url: "workflowStages" },
      { name: "carders", url: "carders" },
      { name: "documentActions", url: "documentActions" },
      { name: "funds", url: "funds" },
    ],
    state: {
      id: 0,
      document_type_id: 0,
      workflow_id: 0,
      name: "",
      label: "",
      icon: "",
      service: "",
      description: "",
      type: "staff",
      requirements: [],
      selectedRequirements: [],
      selectedBlocks: [],
      workflow: null,
      content: [],
      meta_data: null,
      signature_type: "none",
      with_date: 0,
    },
    actions: [
      {
        label: "manage",
        icon: "ri-settings-3-line",
        variant: "success",
        conditions: [],
        operator: "and",
        display: "Manage",
      },
      {
        label: "configurator",
        icon: "ri-flow-chart",
        variant: "dark",
        conditions: [],
        operator: "and",
        display: "Workflow",
      },
      {
        label: "builder",
        icon: "ri-layout-3-line",
        variant: "info",
        conditions: [],
        operator: "and",
        display: "Template",
      },
      {
        label: "configuration",
        icon: "ri-settings-3-line",
        variant: "danger",
        conditions: [],
        operator: "and",
        display: "Configuration",
      },
    ],
  };
