import { ViewsProps } from "../BaseRepository";

export const documentCategoryViews: ViewsProps[] = [
  {
    title: "List of Document Categories",
    server_url: "documentCategories",
    component: "DocumentCategories",
    frontend_path: "/specifications/document-categories",
    type: "index",
    tag: "Add Category",
    mode: "list",
  },
  {
    title: "Create Category",
    server_url: "documentCategories",
    component: "DocumentCategory",
    frontend_path: "/specifications/document-categories/create",
    type: "form",
    tag: "",
    mode: "store",
    action: "Add Category",
    index_path: "/specifications/document-categories",
  },
  {
    title: "Manage Category",
    server_url: "documentCategories",
    component: "DocumentCategory",
    frontend_path: "/specifications/document-categories/:id/manage",
    type: "form",
    tag: "",
    mode: "update",
    action: "Update Record",
    index_path: "/specifications/document-categories",
  },
  {
    title: "Document Category Signatories",
    server_url: "documentCategories",
    component: "DocumentCategorySignatories",
    frontend_path: "/specifications/document-categories/:id/signatories",
    type: "raw",
    tag: "",
    mode: "update",
    action: "Update Signatories",
    index_path: "/specifications/document-categories",
  },
  {
    title: "Document Category Workflow",
    server_url: "documentCategories",
    component: "DocumentWorkflow",
    frontend_path: "/specifications/document-categories/:id/workflow",
    type: "form",
    tag: "",
    mode: "update",
    action: "Update Document Workflow",
    index_path: "/specifications/document-categories",
  },
  {
    title: "Document Category Template Builder",
    server_url: "documentCategories",
    component: "DocumentTemplateBuilder",
    frontend_path: "/specifications/document-categories/:id/builder",
    type: "builder",
    tag: "",
    mode: "update",
    action: "Update Template",
    index_path: "/specifications/document-categories",
  },
  {
    title: "Document Category Configuration",
    server_url: "documentCategories",
    component: "DocumentCategoryConfiguration",
    frontend_path: "/specifications/document-categories/:id/configuration",
    type: "configuration",
    tag: "",
    mode: "update",
    action: "Update Configuration",
    index_path: "/specifications/document-categories",
  },
];
