import { ConfigProp } from "../BaseRepository";
import { ProductResponseData } from "./data";

export const productConfig: ConfigProp<ProductResponseData> = {
  fillables: [
    "product_category_id",
    "department_id",
    "product_brand_id",
    "primary_vendor_id",
    "name",
    "label",
    "code",
    "description",
    "restock_qty",
    "reorder_point",
    "max_stock_level",
    "track_batches",
    "owner",
    "request_on_delivery",
    "out_of_stock",
    "is_blocked",
    "measurements",
  ],
  associatedResources: [
    { name: "categories", url: "productCategories" },
    { name: "departments", url: "departments" },
    { name: "measurementTypes", url: "measurementTypes" },
  ],
  state: {
    id: 0,
    product_category_id: null,
    department_id: null,
    product_brand_id: null,
    primary_vendor_id: null,
    name: "",
    label: "",
    code: "",
    description: "",
    restock_qty: 0,
    reorder_point: 0,
    max_stock_level: 0,
    track_batches: false,
    owner: "store",
    request_on_delivery: false,
    out_of_stock: false,
    is_blocked: false,
    measurements: [],
  },
  actions: [
    {
      label: "manage",
      icon: "ri-settings-3-line",
      variant: "success",
      conditions: [],
      operator: "and",
      display: "Manage",
    },
    {
      label: "view",
      icon: "ri-eye-line",
      variant: "dark",
      conditions: [],
      operator: "and",
      display: "View",
    },
  ],
};
