import { ConfigProp } from "../BaseRepository";
import { InboundResponseData } from "./data";

export const inboundConfig: ConfigProp<InboundResponseData> = {
  fillables: [
    "received_by_id",
    "authorising_officer_id",
    "department_id",
    "vendor_id",
    "from_name",
    "from_email",
    "from_phone",
    "ref_no",
    "summary",
    "instructions",
    "analysis",
    "mailed_at",
    "received_at",
    "published_at",
    "assignable_id",
    "assignable_type",
    "security_class",
    "channel",
    "priority",
    "status",
    "file_uploads",
    "ocr_available",
    "ocr_index_version",
  ],
  associatedResources: [
    { name: "vendors", url: "vendors" },
    { name: "users", url: "users" },
    { name: "departments", url: "departments" },
    { name: "groups", url: "groups" },
  ],
  state: {
    id: 0,
    received_by_id: 0,
    authorising_officer_id: 0,
    department_id: 0,
    vendor_id: 0,
    from_name: "",
    from_email: "",
    from_phone: "",
    ref_no: "",
    summary: "",
    instructions: [],
    analysis: {},
    mailed_at: "",
    received_at: "",
    published_at: "",
    assignable_id: 0,
    assignable_type: "",
    security_class: "public",
    channel: "email",
    priority: "low",
    status: "pending",
    uploads: [],
    file_uploads: [],
    ocr_available: false,
    ocr_index_version: 0,
  },
  actions: [
    {
      label: "manage",
      icon: "ri-settings-3-line",
      variant: "success",
      conditions: [],
      operator: "and",
      display: "Manage",
    },
    {
      label: "view",
      icon: "ri-eye-line",
      variant: "dark",
      conditions: [],
      operator: "and",
      display: "View",
    },
  ],
};
