import { ConfigProp } from "../BaseRepository";
import { ProjectResponseData } from "./data";

export const projectConfig: ConfigProp<ProjectResponseData> = {
  fillables: [
    "user_id",
    "department_id",
    "threshold_id",
    "project_category_id",
    "code",
    "title",
    "description",
    "total_proposed_amount",
    "total_approved_amount",
    "variation_amount",
    "sub_total_amount",
    "vat_amount",
    "markup_amount",
    "proposed_start_date",
    "proposed_end_date",
    "type",
    "status",
    "service_charge_percentage",
  ],
  associatedResources: [
    { name: "thresholds", url: "thresholds" },
    { name: "projectCategories", url: "projectCategories" },
  ],
  state: {
    id: 0,
    user_id: 0,
    department_id: 0,
    threshold_id: 0,
    project_category_id: 0,
    service_charge_percentage: 0,
    code: "",
    title: "",
    description: "",
    total_proposed_amount: 0,
    total_approved_amount: 0,
    variation_amount: 0,
    sub_total_amount: 0,
    vat_amount: 0,
    markup_amount: 0,
    proposed_start_date: "",
    proposed_end_date: "",
    approved_start_date: "",
    approved_end_date: "",
    actual_end_date: "",
    type: "third-party",
    status: "pending",
  },
  actions: [
    {
      label: "manage",
      icon: "ri-settings-3-line",
      variant: "success",
      conditions: [],
      operator: "and",
      display: "Manage",
    },
  ],
};
