import { ConfigProp } from "../BaseRepository";
import { ProjectProgramResponseData } from "./data";

export const projectProgramConfig: ConfigProp<ProjectProgramResponseData> = {
  fillables: [
    "title",
    "description",
    "department_id",
    "ministry_id",
    "project_category_id",
    "planned_start_date",
    "planned_end_date",
    "status",
    "priority",
    "strategic_alignment",
  ],
  associatedResources: [
    { name: "departments", url: "departments" },
    { name: "projectCategories", url: "projectCategories" },
    { name: "users", url: "users" },
  ],
  state: {
    id: 0,
    code: "",
    title: "",
    description: "",
    user_id: 0,
    department_id: 0,
    ministry_id: null,
    project_category_id: null,
    total_estimated_amount: 0,
    total_approved_amount: 0,
    total_actual_cost: 0,
    planned_start_date: "",
    planned_end_date: "",
    actual_start_date: null,
    actual_end_date: null,
    status: "concept",
    priority: "medium",
    strategic_alignment: "",
    overall_progress_percentage: 0,
    overall_health: "on-track",
    is_archived: false,
    archived_at: null,
    archived_by: null,
    created_at: "",
    updated_at: "",
    deleted_at: "",
  },
  actions: [
    {
      label: "manage",
      icon: "ri-folder-settings-line",
      variant: "success",
      conditions: [],
      operator: "and",
      display: "Manage Program",
    },
    {
      label: "view",
      icon: "ri-list-check-2",
      variant: "info",
      conditions: [],
      operator: "and",
      display: "View Phases",
    },
  ],
};

