import { ConfigProp } from "../BaseRepository";
import { ClaimResponseData } from "./data";

export const claimConfig: ConfigProp<ClaimResponseData> = {
  fillables: [
    "total_amount_spent",
    "total_amount_approved",
    "total_amount_retired",
    "type",
    "status",
    "sponsoring_department_id",
    "title",
    "workflow_id",
    "expenses",
    "start_date",
    "end_date",
    "document_category_id",
    "document_type_id",
    "supporting_documents",
    "code",
    "deletedExpenses",
    "deletedUploads",
  ],
  associatedResources: [
    { name: "allowances", url: "allowances" },
    { name: "cities", url: "cities" },
    { name: "departments", url: "departments" },
    { name: "documentTypes", url: "documentTypes" },
    { name: "documentCategories", url: "documentCategories" },
    { name: "workflows", url: "workflows" },
    { name: "tripCategories", url: "tripCategories" },
  ],
  state: {
    id: 0,
    code: "",
    sponsoring_department_id: 0,
    document_category_id: 0,
    document_type_id: 0,
    workflow_id: 0,
    title: "",
    total_amount_spent: 0,
    total_amount_approved: 0,
    total_amount_retired: 0,
    type: "claim",
    status: "pending",
    start_date: "",
    end_date: "",
    supporting_documents: [],
    filename: "",
    trips: [],
    expenses: [],
    uploads: [],
    deletedExpenses: [],
    deletedUploads: [],
  },
  actions: [
    {
      label: "manage",
      icon: "ri-settings-3-line",
      variant: "success",
      conditions: [],
      operator: "and",
      display: "Manage",
    },
  ],
};
