import { ViewsProps } from "../BaseRepository";

export const claimViews: ViewsProps[] = [
  {
    title: "List of Claims",
    server_url: "claims",
    component: "Claims",
    frontend_path: "/hub/claims",
    type: "card",
    tag: "Register Claim",
    mode: "list",
    pointer: "categories",
  },
  {
    title: "Claim Categories",
    server_url: "documentCategories",
    component: "ClaimCategories",
    frontend_path: "/hub/claims/categories",
    type: "card",
    tag: "",
    mode: "list",
    index_path: "/hub/claims",
    pointer: "/hub/claims/create",
  },
  {
    title: "Register Claim",
    server_url: "claims",
    component: "Claim",
    frontend_path: "/hub/claims/:categoryId/create",
    type: "form",
    tag: "",
    mode: "store",
    action: "Register Claim",
    index_path: "/hub/claims",
  },
  {
    title: "Manage Claim",
    server_url: "claims",
    component: "Claim",
    frontend_path: "/hub/claims/:categoryId/:id/manage",
    type: "form",
    tag: "",
    mode: "update",
    action: "Update Claim",
    index_path: "/hub/claims",
  },
  {
    title: "Claim Documentation",
    server_url: "claims",
    component: "ClaimDetail",
    frontend_path: "/hub/claims/:categoryId/:id/view",
    type: "page",
    tag: "",
    mode: "update",
    action: "Update Claim",
    index_path: "/hub/claims",
    documentControl: ["ClaimDetails", "ClaimUpdates"],
    tabs: [
      {
        title: "Draft",
        label: "draft",
        component: "ClaimAppendSignature",
        icon: "ri-draft-line",
        variant: "success",
        endpoint: "claim/updates",
        status: "registered",
        hasFile: true,
        appendSignature: true,
        isDefault: true,
      },
      {
        title: "Summary",
        label: "summary",
        component: "ClaimDetails",
        icon: "ri-booklet-line",
        variant: "info",
        endpoint: "claims",
        status: "view",
        hasFile: false,
        appendSignature: false,
        isDefault: false,
      },
      {
        title: "Files",
        label: "files",
        component: "DocumentUploads",
        icon: "ri-book-line",
        variant: "dark",
        endpoint: "claim/updates",
        status: "verified",
        hasFile: true,
        appendSignature: false,
        isDefault: false,
      },
      {
        title: "Updates",
        label: "updates",
        component: "DocumentUpdates",
        icon: "ri-progress-3-line",
        variant: "warning",
        endpoint: "claim/updates",
        status: "updated",
        hasFile: false,
        appendSignature: false,
        isDefault: false,
      },
      {
        title: "Print",
        label: "print",
        component: "PrintDocument",
        icon: "ri-printer-line",
        variant: "secondary",
        endpoint: "claim/updates",
        status: "printed",
        hasFile: true,
        appendSignature: false,
        isDefault: false,
      },
      {
        title: "Danger Zone",
        label: "danger-zone",
        component: "DocumentReverse",
        icon: "ri-alarm-warning-line",
        variant: "danger",
        endpoint: "claim/updates",
        status: "reversed",
        hasFile: false,
        appendSignature: false,
        isDefault: false,
      },
    ],
  },
];
