import { ViewsProps } from "../BaseRepository";

export const folderViews: ViewsProps[] = [
  {
    title: "Desk",
    server_url: "documents",
    component: "Folders",
    frontend_path: "/desk/folders",
    type: "card",
    tag: "Create Document",
    mode: "list",
  },
  {
    title: "Select Document Category",
    server_url: "documents",
    component: "Categories",
    frontend_path: "/desk/folders/create",
    type: "card",
    tag: "",
    mode: "store",
    action: "Add Folder",
    index_path: "/desk/folders",
  },
  {
    title: "Generate Document",
    server_url: "documents",
    component: "DocumentBuilder",
    frontend_path: "/desk/folders/category/:id/create",
    type: "generator",
    tag: "",
    mode: "store",
    action: "Add Folder",
    index_path: "/desk/folders/create",
  },
  {
    title: "Edit Generated Document",
    server_url: "documents",
    component: "DocumentBuilder",
    frontend_path: "/desk/folders/category/:id/document/:documentId/edit",
    type: "generator",
    tag: "",
    mode: "update",
    action: "Edit Document",
    index_path: "/desk/folders",
  },
  {
    title: "Build Document",
    server_url: "documents",
    component: "BuildDocument",
    frontend_path: "/desk/folders/category/:id/build",
    type: "generator",
    tag: "",
    mode: "store",
    action: "Add Folder",
    index_path: "/desk/folders/create",
  },
  {
    title: "Manage Folder",
    server_url: "documents",
    component: "Folder",
    frontend_path: "/desk/folders/:id/manage",
    type: "docket",
    tag: "",
    mode: "update",
    action: "Update Record",
    index_path: "/desk/folders",
  },
];
